@startuml 
hide footbox
actor 读者
actor 管理员
读者 -> 管理员 :提交还书请求
box "归还图书"
管理员 -> 图书 :登录系统
管理员 -> 图书 :查询图书信息
管理员 -> 借阅记录 :查询借阅信息
管理员 -> 借阅记录 :是否逾期
借阅记录 -> 逾期记录 :如果逾期
逾期记录 ->罚款细则:逾期处罚
借阅记录->图书 :未逾期还书成功
图书 -> 归还记录:记录还书信息
end box
管理员 <-- 归还记录 :返回
读者 <-- 管理员 :返回还书成功信息
@enduml